### ISSUE TITLE
Handling multiple ingresses

### ISSUE THREAD

**Issue by radrad** [endless001/sail-proxy#1]
First of all, thank you for creating this repo. 

Can you comment on this as I see you are using kubernetes.io/ingress.class annotation whis is deprecated from kubernetes v1.22+.
https://kubernetes.github.io/ingress-nginx/user-guide/multiple-ingress/
To fix this problem, use [IngressClasses](https://kubernetes.io/docs/concepts/services-networking/ingress/#ingress-class). The 
Is this about envisioning multiple ingress controllers being used with sail-proxy?

I woud like understand how sail-proxy is related to these modules:
[Kubernetes.Controller](https://github.com/microsoft/reverse-proxy/tree/release/latest/src/Kubernetes.Controller)
[Kubernetes.Protocol](https://github.com/microsoft/reverse-proxy/tree/release/latest/src/Kubernetes.Protocol)
[OperatorFramework](https://github.com/microsoft/reverse-proxy/tree/release/latest/src/OperatorFramework)
Can you please provide a readme.txt or write an article or create a video where you are sharing how what are the goals of this project and how to use it, roadmap, is it going to be integrated with some software. I see you keep commiting more code. 
What is left to be done to be fully usefull. I am debating if I should use NGINX or this project. What is missing from sail-proxy to be full production ready? Can you read below and comment if this project can be used to create a self SaaS onboaring for tenants?

I didn't check, but do you use these projects/dll references in sail-proxy and you build on top of them?
How does it all fit together? 
I belive from what I see this allows sail-proxy (reverse-proxy wrapper) to be used as an ingress controller if installed in a container in kubernetes and it can be used instead of NGINX to dynaically receive routing from new domains, subdomains, url based routing
and that there is a background job that monitors incomming ingress resource creation with appropriate annotations and based on that signals reverse-proxy to refresh its routing and cluster settings.

I posted related question in this discussion:
https://github.com/digitalocean/Kubernetes-Starter-Kit-Developers/discussions/195

I used a customized Yarn reverse proxy as an api gateway where I handled authentication
and I enriched JWT token with extra claims which was later used to downstream services.
I used file based configuration for setting clusters and routes.
I new there was a way to create an external configuration provider that will signal the reverse proxy to adjust its routers and clusters.
I am trying to understand how will this app needs to be installed in kubernetes enviroment.
I am a c# develper and I would like to use it as much as I can and not use "go" language.
I would like to port/convert AWS aws-saas-factory-eks-reference-architecture solution to build self provisioned SaaS app for tenants
using DigitalOcean using https://abp.io/ framework (https://github.com/abpframework/abp)  which has application level multitenancy built it to allow one app instance to serve multiple tenants where some tenants can havce their own DB instance and some can used a shared DB instance 
This is how AWS envision multitenancy in a share kubernetes cluster:
https://aws.amazon.com/blogs/apn/building-a-multi-tenant-saas-solution-using-amazon-eks/
https://github.com/aws-samples/aws-saas-factory-eks-reference-architecture 
Building SaaS on AWS - Deep Dive: Architecting multi-tenant SaaS on EKS
https://youtu.be/kfSFODrdVus?t=2606

Thank you
Rad

**Comment by lqlive** [comment]
Thank you very much for following this repo  
The current repo is doing some experiments with canary, circuit breaker, speed limiter, these experiments are done, and then the current project is improved

Thank you

**Comment by endless001** [comment]
Currently the project can handle multiple entries, and the project can be deployed using helm
provide some sample https://github.com/endless001/sail-proxy/tree/main/samples/ingress
